
#GET http://localhost:3000/users/1
#authorization: secret-token
#Content-Type: application/json


#GET http://localhost:3000/users/search?name=ivan&age=23
#Content-Type: application/json


GET http://localhost:3000/users


#POST http://localhost:3000/users
#Content-Type: application/json
#
#{
#  "name": "Maria 3",
#  "bio": "dsfsfsfdfs"
#}


#PATCH http://localhost:3000/users/1
#Content-Type: application/json
#
#{
#  "bio": "Ппросто Маааарииияя"
#}

#DELETE http://localhost:3000/users/3

#POST http://localhost:3000/users
#Content-Type: application/json
#
#{
#  "name": "ГРандорф 2"
#}
