
#GET http://localhost:3000/users/1
#Content-Type: application/json


#GET http://localhost:3000/users/search?name=ivan&age=23
#Content-Type: application/json


GET http://localhost:3000/users


#POST http://localhost:3000/users
#Content-Type: application/json
#
#{
#  "name": "Maria 3",
#  "bio": "dsfsfsfdfs"
#}


